
services:
  web:
    build:
      context: .
    image: luri/php-nginx
    environment:
      - APP_PORT
    ports:
      - "${APP_PORT}:80"
#    volumes:
#      - ./src:/app
    env_file:
      - .env
